version: '3.7'
services:
  sdk:
    build:
      context: .
      args:
        - NPMRC
    volumes: 
      - .:/code
    environment:
      - SMARTY_AUTH_ID
      - SMARTY_AUTH_TOKEN
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
